### ISSUE TITLE
Add {description} email tag

### ISSUE THREAD

**Issue by erommel** [Arsenal21/stripe-payments#107]
As requested here:

https://wordpress.org/support/topic/description-tag-missing/#post-11881522

**Comment by Arsenal21** [comment]
We have another request of this here so lets add this one to the email merge tag list:
https://s-plugins.com/forums/topic/adding-product-description-to-email-confirmation/

**Comment by Arsenal21** [comment]
Handled by this:
https://github.com/Arsenal21/stripe-payments/pull/189
