### ISSUE TITLE
Easy way to attach payment popup to an existing button or a link

### ISSUE THREAD

**Issue by erommel** [Arsenal21/stripe-payments#116]
https://wordpress.org/support/topic/how-to-add-a-stripe-link-to-a-button-built-in-in-my-wp-theme/

Some people prefer to use theme builders etc. to create payment pages. Some of them do not support shortcodes normally. Or some people just don't want to make any additional steps to configure the stuff as needed (which I can understand).

What we need is an easy way to attach payment popup to an existing button or a link. We do have functionality to attach payment popup to any element by adding CSS class ''asp-attach-product-123" (123 is product ID). We should also add functionality to attach payment popup to a link by putting a specific URL to href attribute on <a> tag for situations where CSS class can't be added by a user. Something like this:

`<a href="https://example.com/some-url-with-product-id/">Pay Now</a>`

Will investigate this further.

**Comment by erommel** [comment]
I've added "Embed" metabox to product edit page where users can see available methods to attach embed product on page \ attach payment popup to any element.

![embed_metabox](https://user-images.githubusercontent.com/310848/70450596-abf6d980-1aac-11ea-9042-8a350e2acb61.png)

@Arsenal21 , let me know what you think.

**Comment by Arsenal21** [comment]
wow! that looks nice. Is this in the code for me to pull and test it?

**Comment by erommel** [comment]
All the changes are in dev branch at the moment https://github.com/Arsenal21/stripe-payments/tree/dev

**Comment by Arsenal21** [comment]
Nice. I will create the documentation
