### ISSUE TITLE
Translate Stripe popup window strings

### ISSUE THREAD

**Issue by mbrsolution** [Arsenal21/stripe-payments#120]
Hi, someone in the forum requested to know if the following strings marked in red in the image below are translatable?

![stripe-payment-forum-french-word-issue-@masterhealerwp](https://user-images.githubusercontent.com/38054628/71300079-9d2df200-23dd-11ea-9ff0-f4b9deedf6d5.png)

This is the link to the support thread in question.
https://wordpress.org/support/topic/french-words-in-the-payment-popup/

Thank you

**Comment by erommel** [comment]
Those are handled automatically by Stripe. Stripe detects browser locale and sets those strings accordingly.

What can additionally be done is to make payment popup consider "Stripe Checkout Language" option. Currently, it only works for old API. For new API, it's always "Auto", regardless of the setting. I will make necessary changes.

**Comment by mbrsolution** [comment]
That is a very good idea. I am sure this will make many users happy :)

Well done.
