### ISSUE TITLE
CSS Customization option for the payment popup window

### ISSUE THREAD

**Issue by Arsenal21** [Arsenal21/stripe-payments#137]
Potentially add a textarea somewhere in the Advanced Settings tab where you can add custom CSS that would be loaded on payment popup.

**Comment by erommel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Additional CSS option for payment popup](https://trello.com/c/6lMQwwEK/111-additional-css-option-for-payment-popup)
