### ISSUE TITLE
Construct product price using Variations only

### ISSUE THREAD

**Issue by erommel** [Arsenal21/stripe-payments#141]
As requested by users, there should be an option for a product to construct its price using variations only. Currently, when you set product price to 0, it assumes it is a donation product and displays amount input.

There should be an option added to Variations meta box. When variations are created and the option is enabled, plugin shouldn't display amount input when product price is set to 0. This way users can construct product price using Variations only.

**Comment by Arsenal21** [comment]
Good idea. Maybe there can be a checkbox to enable this new behavior. This new checkbox can be in that variations meta box section. That can be used to override how the "0" price in the main product price field behaves.
