### ISSUE TITLE
Add “State\Province\Region” field to address inputs when applicable

### ISSUE THREAD

**Issue by erommel** [Arsenal21/stripe-payments#149]
No ideas on this one yet, just leaving it here to discuss later.

**Comment by Arsenal21** [comment]
@erommel, 

When the address collection option is enabled, it currently shows the following in the payment popup:
---
Address, City
Country, Postcode
---
Instead, it can show the following in the popup for address (this is more correct to collect a full address so better to have a field for "state" also)
-------
Address, City
State, Postcode
Country
-----------
My question is, can we submit the "state" value to Stripe API? I don't know if they take the parameter or not.

**Comment by erommel** [comment]
>Instead, it can show the following in the popup for address (this is more correct to collect a full address so better to have a field for "state" also)

Thing is, some countries do not have states\provinces etc. and some people are getting annoyed when being requested for a state if they don't have one.

This can be solved by getting a list of countries that have states\provinces etc. and where those are needed for address. I remember I've seen some list like that, will try to find it.

So, on the frontend, if a country selected by a customer has states\provinces - corresponding field should be displayed. If not - it's not displayed.

>My question is, can we submit the "state" value to Stripe API? I don't know if they take the parameter or not.
Yep, they do have a field for state, county, province, or region.

**Comment by appthemes7** [comment]
The state fields can be an optional field. So people can leave it empty and the checkout will go ahead without any issue. 

Also, we can add a CSS tweak in the following documentation to show them how they can hide that field using a little CSS (using the "display: none" property):
https://s-plugins.com/customizing-the-payment-popup-using-css/

The biggest user base of this plugin is from the US. About 95% of the user base is from English countries. All those countries will have the "state" field. So we do need to make the default cater for that user base. Then the other things (for the smaller % of user base) can be handled using little tweaks.

**Comment by Arsenal21** [comment]
The state fields can be an optional field. So people can leave it empty and the checkout will go ahead without any issue.

Also, we can add a CSS tweak in the following documentation to show them how they can hide that field using a little CSS (using the "display: none" property):
https://s-plugins.com/customizing-the-payment-popup-using-css/

The biggest user base of this plugin is from the US. About 95% of the user base is from English countries. All those countries will have the "state" field. So we do need to make the default cater for that user base. Then the other things (for the smaller % of user base) can be handled using little tweaks.

**Comment by erommel** [comment]
Since the plugin is still being used by people from different countries (France, Netherlands, Japan etc), where "State\Province" is not required (or not obligatory) in the address, I'd suggest the following:

Create additional settings option, something like "Hide State\Province Input". It would be **disabled** by default for NEW plugin installs. For existing installs, we would make it **enabled** in order to preserve current payment popup look. Users can disable it if they wish to add "State\Province" field to the existing popup.

What do you think?

**Comment by Arsenal21** [comment]
That sounds good to me.
