### ISSUE TITLE
FPX local payment method requested

### ISSUE THREAD

**Issue by mbrsolution** [Arsenal21/stripe-payments#151]
Hi, I am not sure if you have this request added to your to do list. Someone in the forum requested this. 

Here is the forum link.
https://wordpress.org/support/topic/fpx-local-payment-method-2/

This is supported by Stripe.

https://stripe.com/docs/payments/fpx

If you need more information, please let me know.

Thank you

**Comment by erommel** [comment]
Yep, this has been added as to-do here https://github.com/Arsenal21/stripe-payments-addons/issues/64
