### ISSUE TITLE
Add IDs to popup form fields containers

### ISSUE THREAD

**Issue by erommel** [Arsenal21/stripe-payments#171]
This should be useful for people wanting to re-arrange fields positions.

**Comment by erommel** [comment]
Form fields re-order example:

Current default fields order:
[Quantity]
[Custom Fields]
[Variations]

We want to re-order them like this:
[Variations]
[Quantity]
[Custom Fields]

Following custom CSS should be added to payment form:

```
#payment-form {
display: flex;
flex-direction: column;
}

#variations-cont {
order: -3;
}

#quantity-cont {
order: -2;
}

#custom-fields-cont {
order: -1;
}
```

Playing with `order` property can move fields anywhere on the form (including after payment button if value is >0).

**Comment by erommel** [comment]
https://caniuse.com/#feat=flexbox

This looks to be supported by all current major browsers. IE has limited support with bugs, so this should be specifically tested against IE11.

**Comment by Arsenal21** [comment]
Wow! I like it :) 

When this is available and usable, please create a trello task so I can create a usage documentation on the site.

**Comment by erommel** [comment]
@Arsenal21 , I have added some more examples to my comment here https://github.com/Arsenal21/stripe-payments/issues/171#issuecomment-660280571

**Comment by erommel** [comment]
In the future, we can make a GUI (similar to Variations or Additional Custom Fields plugin) where users can re-arrange the fields how they want globally and\or on per-product basis. But for now, CSS-way should be sufficient.
