### ISSUE TITLE
Incompatibility with SG Optimizer plugin

### ISSUE THREAD

**Issue by erommel** [Arsenal21/stripe-payments#180]
There are several issues reported by users lately (mostly "Invalid Security Token" error) that are hosted by SiteGround with SG Optimizer plugin enabled https://wordpress.org/plugins/sg-cachepress/

This needs to be researched to find possible workaround.

**Comment by Arsenal21** [comment]
It is because it is serving a cached page which has stale security token values?

Normally for eStore, we use something like this to not serve a cached page to someone who clicked the "add to cart" button:
http://www.tipsandtricks-hq.com/forum/topic/using-the-plugins-together-with-wp-super-cache-plugin
http://www.tipsandtricks-hq.com/forum/topic/using-the-plugins-with-w3-total-cache-plugin

Maybe that isn't possible for our stripe plugin though.

**Comment by erommel** [comment]
Can't login to see those forum posts as I'm not a customer :)

But I think this might not be related as SiteGround seem to be more intrusive than your standard WP caching plugins. It even minifies and combines payment popup JS and CSS, which standard caching plugins can't do as those JS and CSS files are not outputted via default WP methods.

SG Optimizer has some documentation explaining how to exclude specific pages from caching and\or JS\CSS files from minify\combine programmatically. I will research this.

**Comment by Arsenal21** [comment]
> SG Optimizer has some documentation explaining how to exclude specific pages from caching and\or JS\CSS files from minify\combine programmatically. I will research this.

okay

If you want me to create a forum account for you on the tthq forum, let me know.

**Comment by erommel** [comment]
Force external caching plugins cache clear when plugin settings are changed https://github.com/Arsenal21/stripe-payments/commit/0d8ca05e3e260ea26600b53d9761076aeba5c724

This helps prevent situations when new settings (like default currency change, Live mode switch etc) aren't applied due to caching.

**Comment by erommel** [comment]
SG Optimizer: placed payment popup inline CSS right after `<head>` tag https://github.com/Arsenal21/stripe-payments/commit/d4e0d8d3d832d85b9b661b42aa2340094001e749

This fixes some visual bugs (like `Test Mode` badge isn't displayed when test mode is enabled) when SG Optimizer `Combine CSS Files` option enabled.

**Comment by erommel** [comment]
This is handled for now. Will re-open if there are more reports on this.
