### ISSUE TITLE
Cannot pass parameters from my cart to Stripe

### ISSUE THREAD

**Issue by benlvovsky** [Arsenal21/stripe-payments#184]
I need to pass parameters like Cart OrderID, UserID, other collected details to popup and then to Stripe. Maybenot even into popup but to Stripe metadata. Maybe it will be enough to in my database to link somehow data collected in my dialog box with Stripe transaction. How do I do it? Is it possible at all?

**Comment by Arsenal21** [comment]
This is not possible unfortunately.
