### ISSUE TITLE
Issue with email aliases containing plus sign

### ISSUE THREAD

**Issue by ovidiubica** [Arsenal21/stripe-payments#193]
[Email subaddressing](https://en.wikipedia.org/wiki/Email_address#Subaddressing) doesn't work with our plugin. Is this something we [should fix](https://wordpress.org/support/topic/bug-emails-containing/#post-14410071)?

**Comment by Arsenal21** [comment]
hmmm... is it the sanitization/validation on the email address field that is breaking that or the wordpress's following function failing?

https://developer.wordpress.org/reference/functions/is_email/

**Comment by ovidiubica** [comment]
We need to dig a bit further, according to [this ticket](https://core.trac.wordpress.org/ticket/53130), it should be working.
