### ISSUE TITLE
Documentation needs to describe how to customize error message too

### ISSUE THREAD

**Issue by erommel** [Arsenal21/stripe-payments#21]
In this tutorial, if payment error occurs, it won't be displayed. https://stripe-plugins.com/customize-the-thank-page-message-of-stripe-payments-plugin/

In order for it to display error message, following shortcode needs to be used:

[accept_stripe_payment_checkout_error]
Oops, something went wrong!
{error_msg}
[/accept_stripe_payment_checkout_error]

If there were no error during the process, the content of this shortcode won't be displayed. And vise versa - if error occured, then only this content will be displayed and the one for success payment won't be.

**Comment by Arsenal21** [comment]
Updated the documenation.
