### ISSUE TITLE
Add custom field data to Stripe metadata

### ISSUE THREAD

**Issue by erommel** [Arsenal21/stripe-payments#27]
Requested by user https://wordpress.org/support/topic/use-of-custom-field-data/

Seems like a good idea in general, so users can see additional details in their Stripe Dashboard.

**Comment by Arsenal21** [comment]
In the future we will create an addon that allows the user to customize multiple custom input fields. That addon could perhaps do this.

**Comment by erommel** [comment]
Well, this doesn't seem too hard to implement. And addon would be adding its fields to metadata as well. Since we already implemented a custom field, I think we should make it available.

But that's definitely your call :-)

**Comment by Arsenal21** [comment]
If its not too difficult then thats fine.
