### ISSUE TITLE
Add {custom_field} to available tags list for custom thank you page

### ISSUE THREAD

**Issue by erommel** [Arsenal21/stripe-payments#28]
Requested by user https://wordpress.org/support/topic/use-of-custom-field-data/

Looks like a good idea.

**Comment by erommel** [comment]
Also added {custom_field}, {custom_field_name} and {custom_field_value} tags to the documentation page https://stripe-plugins.com/customize-the-thank-page-message-of-stripe-payments-plugin/

**Comment by Arsenal21** [comment]
Looks good
