### ISSUE TITLE
Incompatibility issues with various visual builders

### ISSUE THREAD

**Issue by erommel** [Arsenal21/stripe-payments#32]
There are several reports from users that buttons are not properly working when used inside various visual builders like Instabuilder, Inbound Theme, OptimizePress Theme etc. The reason why it's happening is because those themes are breaking standard WP functionality by not allowing plugin to use wp_enqueue_script() and wp_localize_script() functions. As a result, scripts and vars required by plugin are not being inserted into page and after visitor clicks "Buy" button, "Invalid Stripe token" error is produced. Since it's not users' problem, we have to address this.

I've added a new shortcode parameter that works with both buttons and products - compat_mode="1". When it's specified, plugin will inject all required scripts and vars inside the HTML (which is not how WP Codex says it should be, but looks like there is not much of a choice here). So, if a user wants to use button or product shortcode in visual builders, it should look like this:

[asp_product id="123" compat_mode="1"]

**Comment by Arsenal21** [comment]
Looks good
