### ISSUE TITLE
Add options for users to customize some text in the plugin

### ISSUE THREAD

**Issue by erommel** [Arsenal21/stripe-payments#41]
Had several requests on this (this one, for example https://wordpress.org/support/topic/translation-892/). Users want this no only to be translated on their own language, but also have a way to change this text per their own needs.

My idea is to add a new settings section where we can let users customize those messages. We can keep adding more strings there per user requests. The most obvious messages to be added first are:

"Enter amount", "Please enter a valid amount", error messages for not accepting ToS or not filling in required fields etc.

**Comment by Arsenal21** [comment]
I think a similar implementation like the following can be done in the future:
https://wordpress.org/plugins/simple-membership-custom-messages/

**Comment by erommel** [comment]
Thank you for your guidance.

I've created similar addon: https://github.com/Arsenal21/stripe-payments-addons/tree/master/stripe-payments-custom-messages
