### ISSUE TITLE
3D Secure support

### ISSUE THREAD

**Issue by erommel** [Arsenal21/stripe-payments#42]
Not pressing at the moment, but should be implemented sooner or later anyway.

The problem is that current integration method used by plugin (named "checkout") has no 3D Secure support. In order to use it, "elements" integration method should be used instead - https://stripe.com/docs/sources/three-d-secure

According to Stripe, 3D Secure is supported in following countries:

> United States, Canada, Europe, Hong Kong, Singapore, Japan, Australia, and New Zealand

As a solution, we can create an addon that is handling 3D Secure payments. It will be somewhat similar to AliPay addon (since its using synchronous "redirect" integration method), but we would have to have our own form with CC and customer details (address etc).

I will do some more research on this.

**Comment by Arsenal21** [comment]
An addon option sounds good (can be a free addon).

**Comment by erommel** [comment]
In the light of upcoming EU's SCA and Stripe's API modifications to support this, there is sense in adding old API 3D Secure support. We would use new Checkout API which supports 3D Secure by default.

**Comment by Arsenal21** [comment]
Yep, using the new option will be the proper solution. 

Will the checkout work very similar to how it works currently from the customers point of view?

**Comment by erommel** [comment]
Not really. There won't be a payment popup anymore, there will be full page redirect instead.

You can check how it looks here https://stripe.com/docs/payments/checkout#see-how

**Comment by Arsenal21** [comment]
oh okay. I kind of like that simple quick checkout in the popup :(

We should maybe make a checkbox in the advanced settings so people in other countries  can maybe still use the existing checkout style for some time.

**Comment by erommel** [comment]
With new Stripe API changes, we can do two things in a row ;-)

1. Add this new Checkout that would make the checkout process nice and easy via Stripe's hosted page.

2. Add Stripe Elements + PaymentIntent support. Using those, we can make our own popup with any fields we like etc. So customers won't have to prefill some details, then click pay button and fill more details. Everything will be in one popup - custom fields, phone number, quantity\amount inputs etc.

#2 needs to be investigated some more to figure out how 3D Secure 2.0 is handled though. But it's easier to add it now since there are changes required to the code anyway.

**Comment by Arsenal21** [comment]
That sounds good to me.

**Comment by erommel** [comment]
Since new API is supporting 3D Secure, we can consider this one completed.
