### ISSUE TITLE
Discount codes and coupons

### ISSUE THREAD

**Issue by erommel** [Arsenal21/stripe-payments#43]
Looks like people are requesting this feature more often lately.

Any ideas how to implement it properly?

**Comment by Arsenal21** [comment]
Yeah, I was actually going to send you a request to implement something for this. 

Here is how I think it should be implemented.

#1) There should be a NEW menu item called "Coupons". This menu item can be just below the "Orders" menu.

#2) The content of this menu should be very similar to what we have in our Simple cart plugin ( https://wordpress.org/plugins/wordpress-simple-paypal-shopping-cart/ ) 

You can see the coupons interface by going to the following admin area (where simple cart is installed)
wp-admin/admin.php?page=wspsc-discounts

It basically has an option to enable the coupon feature and then configure discount coupons.

#3) When enabled, it should show a text field above the "Buy Now" button of the product that allows the user to enter a coupon. Something like the following maybe.

![screenshot-2018-6-5 simple shopping cart test page test site alpha](https://user-images.githubusercontent.com/6433635/40971165-0afb0eac-6900-11e8-9770-1eef6a62ee21.png)

Or it can be a text link that says "Enter a coupon", when clicked, it pops up or shows the coupon code entry field so the visitor can apply a coupon.

#4) Also, take a look at eStore's coupon menu (wp-admin/admin.php?page=wp_eStore_discounts). It allows you to configure conditional coupons also. Have a look at the "Add a coupon" interface only.

Initially it is okay if there is a simple coupon option only. However, in the future the users will ask for the option to configure conditional coupons (like a coupon that only applies to a particular stripe product). So at least keeping this in mind will help you create the structure that can be expanded easily in the future when we want to implement some conditional coupon options.

What do you think?

**Comment by erommel** [comment]
Implemented in version 1.9.1
