### ISSUE TITLE
Check for min and max amount when creating a product and displaying payment button

### ISSUE THREAD

**Issue by erommel** [Arsenal21/stripe-payments#50]
We already have the check for variable amount on the fronted (#37), but don't have one on the backend. This confuses users when they create a product with amount like 1 pence (with minimum allowed 30 pence for GBP) and get no warning or error message or whatsoever.

**Comment by Arsenal21** [comment]
good idea

**Comment by erommel** [comment]
Fixed by f0846f4a38f4b5941f246f8ed411eac408b13953
