### ISSUE TITLE
Offer a feature to allow Variation Control

### ISSUE THREAD

**Issue by Arsenal21** [Arsenal21/stripe-payments#52]
Customers has started to ask about variation pricing option for products. This is something that will need to be added to the plugin (so people can offer different variations)

In WP eStore, we handle variation this way:
https://www.tipsandtricks-hq.com/ecommerce/how-to-use-variation-control-in-wordpress-estore-plugin-345

A slightly more improved version should be added to Stripe payments.

**Comment by erommel** [comment]
Has been implemented.
