### ISSUE TITLE
Bug: apply_filters

### ISSUE THREAD

**Issue by zahardoc** [Arsenal21/stripe-payments#54]
Filters "asp_button_output_before_custom_field" and "asp_button_output_before_tos" in class AcceptStripePaymentsShortcode don't work.
For example,
apply_filters(‘asp_button_output_before_custom_field’, $output, $data);
should be
$output = apply_filters(‘asp_button_output_before_custom_field’, $output, $data);

**Comment by erommel** [comment]
Looks like both mentioned functions was added by me during development of unfinished addon Additional Custom Fields: https://github.com/Arsenal21/stripe-payments/blame/5585ad072ddf213d68193d84f5ce11ce1cd48a1f/stripe-payments/public/includes/class-shortcode-asp.php#L609 https://github.com/Arsenal21/stripe-payments/blame/5585ad072ddf213d68193d84f5ce11ce1cd48a1f/stripe-payments/public/includes/class-shortcode-asp.php#L634

So those are not needed at the moment, but will be needed definitely, so yeah, it makes sense to fix them.

@zahardoc , you were asking for some repo access here https://wordpress.org/support/topic/bug-apply_filters/#post-10649712 , but actually you need to do it in a bit different way:

1. Clone the repo via github.
2. Make the changes you mentioned.
3. Make pull request to this repo.

I think this should do it.

**Comment by zahardoc** [comment]
@erommel  Could you please describe the 3d step? Usually, I do it this way:
1. Clone repository to my machine.
2. Create new branch like this: `git branch -b new_branch`.
3. Make changes and commit them.
4. Push new branch to the repository: `git push origin new_branch`.
5. Make pull request from "Pull requests" tab.

For now, I can't push new branch there - it says "Permission to Arsenal21/stripe-payments.git denied to zahardoc".
Did I miss something?

**Comment by erommel** [comment]
Sorry for not making myself clear.

Just add step 0:

0. Fork the repo into your github.

Then do your steps.

6. Make pull request from your fork to our repo.

I have made an example pull request to one of your repos using the method I described: https://github.com/zahardoc/importer-from-maxsite/pull/4

**Comment by zahardoc** [comment]
Thank you for clearing it up, will do it now.

**Comment by erommel** [comment]
Merged. Thank you!
