### ISSUE TITLE
Per-product success email

### ISSUE THREAD

**Issue by erommel** [Arsenal21/stripe-payments#58]
As requested by customer:

> 2. Email for physical products
> 
> So when we send an email to customer after he/she buys something a common email goes to them. This is not ideal for a physical product because we are not offering anything to download and I still have to add the download link because it is a common email and goes out for both downloads and physical products. Can we have the option to send an email based on the product category? Or customize the emails we send out at the product level?

**Comment by Arsenal21** [comment]
Maybe it can be offered via an addon like the following one?
https://www.tipsandtricks-hq.com/ecommerce/wp-estore-post-payment-actions-addon-1691

**Comment by erommel** [comment]
This functionality has been implemented in Post Payment Actions (PPA) addon: https://github.com/Arsenal21/stripe-payments-addons/tree/master/stripe-payments-post-payment-actions
