### ISSUE TITLE
Store shipping address in metadata

### ISSUE THREAD

**Issue by erommel** [Arsenal21/stripe-payments#65]
Requested by users, sounds like a good idea. Stripe does not allow to store Shipping address in payment info, only Billing address. But we can get over it by saving it as metadata.

**Comment by Arsenal21** [comment]
Yep, good idea. It will be needed for the users selling physical goods.

**Comment by erommel** [comment]
Done https://github.com/Arsenal21/stripe-payments/commit/a8831e334fd8ab0dc700541de28e82151e7f0169
