### ISSUE TITLE
[Feature] - Option to Show User Orders/Transactions

### ISSUE THREAD

**Issue by Arsenal21** [Arsenal21/stripe-payments#70]
A feature to show order history of the customer in a page. Here is a rough summary of how we can handle this:

1. When orders are saved, add the WP User's ID to the orders meta data (if the user is logged into the site at the time of the transaction). The plugin will basically always save the WP User's ID to the order meta (if the user is logged-in).
2. Create a new shortcode that can be added to a page. [asp_show_my_transactions]
3. This shortcode can display all the transactions (of the currently logged-in user)(if any).

**Comment by erommel** [comment]
https://github.com/Arsenal21/stripe-payments/commit/d28d05c13093414dab686488270fd66cf1fa622a
