### ISSUE TITLE
Avoid PHP Sessions usage

### ISSUE THREAD

**Issue by erommel** [Arsenal21/stripe-payments#91]
https://wordpress.org/support/topic/session-cookie-making-site-slow-and-service-unavailable/

Generally, WP itself is not using PHP Sessions. Also some caching (and other) plugins aren't working properly due to Sessions.

Since Sessions are used only for passing and displaying results on checkout results page, those could be replaced with other methods, which would let us get rid of Sessions completely. https://github.com/Arsenal21/stripe-payments/search?q=%22%24_SESSION%22&type=Code

**Comment by Arsenal21** [comment]
ummmm okay. But only do this change if you can guarantee that nothing existing will break :)
